name: Read hello.txt file

on:
  push:
    branches:
      - main

jobs:
  read-hello-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Read and output hello.txt content
        run: |
          cat hello.txt
