apiVersion: v1
kind: Service
metadata:
  name: pharmacy-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: pharmacy
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
