apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-deploy
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels: { app: pharmacy }
  template:
    metadata:
      labels: { app: pharmacy }
    spec:
      containers:
      - name: web
        image: REPLACE_ME_DH_USER/pharmacy:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
