name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # main branch এ push হলেই trigger হবে

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/your-repo   # তোমার repo path দাও এখানে
            git pull origin main
            docker-compose down
            docker-compose up -d --build
