name: CI for Dev Branch

on:
  push:
    branches: [ "stage" ]   # শুধু dev branch এ push হলে run হবে

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: "18"

    #   - name: Install dependencies
    #     run: npm install

    #   - name: Run tests
    #     run: npm test