name: Deploy to EC2

on:
  push:
    branches:
      - main   # শুধু main branch এ push হলেই run হবে

jobs:
  deploy:
    runs-on: ubuntu-latest   # এখানে self-hosted এর বদলে ubuntu-latest ব্যবহার করো
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/pharmacy/pharmacy || exit 1
            git pull
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose ps
